language: java
sudo: required
jdk: oraclejdk8
env:
  global:
  - ANDROID_API_LEVEL=21
  - EMULATOR_API_LEVEL=21
  - ANDROID_BUILD_TOOLS_VERSION=21.1.2
  - ANDROID_ABI=armeabi-v7a
  - ADB_INSTALL_TIMEOUT=20
  - ANDROID_TAG=google_apis
  - ANDROID_HOME=${TRAVIS_BUILD_DIR}/android-sdk
  - PATH=${ANDROID_HOME}/:${ANDROID_HOME}/tools/:${ANDROID_HOME}/platform-tools/:${PATH}

android:
  components:
  - tools
  - platform-tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-$ANDROID_API_LEVEL
  - android-$EMULATOR_API_LEVEL
  - addon-google_apis-google-$ANDROID_API_LEVEL
  - addon-google_apis-google-$EMULATOR_API_LEVEL
  - extra-google-google_play_services
  - extra-android-support
  - extra-google-m2repository
  - extra-android-m2repository
  - sys-img-armeabi-v7a-google_apis-$ANDROID_API_LEVEL
  - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API_LEVEL
before_script:
  - echo no | android create avd --force -n test -t "android-"$EMULATOR_API_LEVEL --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb -s emulator-5554 shell input keyevent 82 &
  - gem install cucumber
